spring:
  application:
    name: cnwasshu
  profiles:
    active: local

kakao-mobility:
  rest-api-key: ${KAKAO_MOBILITY_REST_API_KEY:}
  base-url: ${KAKAO_MOBILITY_BASE_URL:https://apis-navi.kakaomobility.com}
